//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Lexicon
{
    public int ID { get; set; }
    public string Word { get; set; }
    public Nullable<decimal> Rate { get; set; }
}

public partial class TextDocument
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public decimal Rate { get; set; }
}
